# Generated by Django 5.1.5 on 2025-01-28 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=20)),
                ('task_name', models.CharField(max_length=100)),
                ('assigned_by', models.CharField(max_length=100)),
                ('assigned_to', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Onprocess', 'Onprocess'), ('Completed', 'Completed')], max_length=100)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='taskmanager.task')),
            ],
        ),
    ]
